[project]
name = "backups-tar-gzip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.14.0",
    "pyyaml>=6.0.3",
]

[project.scripts]
backups-tar-gzip = "backups_tar_gzip:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
