defaults:
  destination: /home/jonny/backups
  excludes: []
  compress: true
  retention:
    consolidate_after: 7 # Number of days
    keep_archives: 3

projects:
  - project_name: ollama
    backup_filename: ollama_backup.tar.gz
    destination: /home/jonny/backups
    source: /home/jonny/ollama
    # includes = []
    excludes:
      - models
      - stable-diffusion
      - sdnext

  - project_name: bingo
    backup_filename: bingo_backup.tar.gz
    destination: /home/jonny/backups
    source: /home/jonny/bingo
