defaults:
  destination: /home/jonny/backups
  excludes: []
  compress: true
  incremental_filename: backup.inc # Used to track changed between backups.
  retention:
    consolidate_after: 7 # Number of days
    keep_archives: 3

projects:
  ollama:
    backup_filename: ollama_backup.tar.gz
    destination: /home/jonny/backups1
    source: /home/jonny/ollama
    excludes:
      - models
      - stable-diffusion
      - sdnext

  bingo:
    backup_filename: bingo_backup.tar.gz
    includes:
      - /home/jonny/bingo
      - /home/jonny/bingo1
    excludes:
      - .gitignore
